name: Check for typos

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  check-typos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run spellcheck
        uses: crate-ci/typos@v1.35.3
